project_id = "hyzlkqrlodpcmxsnexsg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = {"enabled": true}
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://hyzlkqrlodpcmxsnexsg.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password = true
security_manual_linking_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[edge_functions]
enabled = true
port = 54327

[functions.send-verification]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[analytics]
enabled = false
port = 54328
vector_port = 54329
backend = "postgres"