// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyzlkqrlodpcmxsnexsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5emxrcXJsb2RwY214c25leHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Njg5ODQsImV4cCI6MjA3MzI0NDk4NH0.IYxNLHtu0VOHAVxUuYT8_ON04U0M9ybh_RyULod3Q-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});